version: "2.0"

services:
  grusp-app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: laravel9-alpine
    container_name: ${CONTAINER_NAME_APP}
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=${APP_DOMAIN}
      - VIRTUAL_PORT=8080
      # - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      # - LETSENCRYPT_HOST=${APP_DOMAIN}
    volumes:
      - .:/var/www/localhost
    user: nobody
    depends_on:
      - grusp-db

  grusp-db:
    image: mysql:5.7
    container_name: ${CONTAINER_NAME_DB}
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      NETWORK_ACCESS: internal
    volumes:
      - ${DB_FILES}:/var/lib/mysql

networks:
  default:
    external:
      name: ${NETWORK}
